spring: 
 datasource: 
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/user
  username: root
  password: zklzsm1314
  type: com.alibaba.druid.pool.DruidDataSource
 redis: 
  host: 127.0.0.1
  port: 6379
 rabbitmq: 
  host: 127.0.0.1
  port: 5672
  username: admin
  password: admin
  virtualHost: /
logging: 
 level: debug
